"""
MABE AI Attacker — Hallucination / Retry Module
=================================================

Models the documented behaviour of LLM-based attack agents that report
success on operations that did not actually succeed, and the subsequent
backtrack behaviour when the agent fails to make progress from a node it
falsely believed it had accessed.

EMPIRICAL GROUNDING
-------------------
Source: GTG-1002 (November 2025) — "Claude frequently overstated findings
and occasionally fabricated data during autonomous operations, claiming to
have obtained credentials that didn't work." → Justifies the false_positive_rate
parameter and the hallucinated-success event sequence.

ORDERING GUARANTEE
------------------
The spec (Section 8 and Section 9) is explicit:

    "ORDERING: hallucination check fires FIRST, before BFS queue addition
    and before credential_harvest_probability roll. A hallucinated success:
    logs success=True in the event record, does NOT add the node to the BFS
    queue, does NOT trigger a credential harvest roll."

This ordering is enforced here, not left to the traversal agent. The
check() method returns a HallucinationResult that the traversal agent acts
on — it never needs to implement the ordering logic itself.

CREDENTIAL HARVEST
------------------
When the hallucination check does not fire (real success), check() rolls
credential_harvest_probability and, if triggered, samples a credential
privilege level from the node-type weight distribution. The harvested
Credential object is returned inside HallucinationResult so the traversal
agent can add it to the credential store without knowing the sampling logic.

BACKTRACK EVENTS
----------------
When a hallucination fires, the traversal agent must subsequently emit a
backtrack event (network_connection, attack_step=backtrack) when it fails
to make progress from the hallucinated node. The HallucinationResult flag
`is_hallucination=True` signals this to the traversal agent. The backtrack
event itself is generated by the traversal agent (not here) because it
requires graph context (the node being abandoned) that this module does
not hold.
"""

from __future__ import annotations

import random
from dataclasses import dataclass

from generator.agents.ai_attacker.foothold import Credential
from schema.event import ATTACK_STEP_TTP

# ---------------------------------------------------------------------------
# Privilege hierarchy (mirrors graph_builder.PRIVILEGE_HIERARCHY)
# ---------------------------------------------------------------------------
# Defined here to avoid a circular import with graph_builder.
# Must stay in sync with graph_builder.PRIVILEGE_HIERARCHY.

PRIVILEGE_HIERARCHY = ["standard_user", "service_account", "domain_admin"]


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class HallucinationResult:
    """
    The outcome of a single hallucination check on an auth success event.

    Fields
    ------
    is_hallucination : bool
        True if the success was hallucinated. The traversal agent must:
        - NOT add the node to the BFS queue
        - NOT add any credential to the store
        - Emit a backtrack event when it cannot make progress from this node
        False if the success was real.

    harvested_credential : Credential | None
        A harvested credential if the real-success credential harvest roll
        triggered. None if:
        - is_hallucination is True (harvest never rolled)
        - is_hallucination is False but the harvest roll did not trigger
        The traversal agent adds this to the credential store when non-None.

    privilege_escalation : bool
        True if harvested_credential is non-None and its privilege level
        exceeds the highest privilege currently in the credential store.
        Signals to the traversal agent that the BFS frontier should be
        re-evaluated — new edges may now be traversable.
    """
    is_hallucination: bool
    harvested_credential: Credential | None
    privilege_escalation: bool


# ---------------------------------------------------------------------------
# HallucinationModule
# ---------------------------------------------------------------------------

class HallucinationModule:
    """
    Applies the hallucination check and credential harvest roll to auth
    success events.

    Parameters
    ----------
    params : dict
        The ai_attacker section of behavioral_params.yaml. Reads:
            false_positive_rate                        (default: 0.15)
            credential_harvest_probability             (default: 0.30)
            credential_privilege_weights_by_node_type  (required)
    rng : random.Random
        Seeded RNG from simulate.py.
    """

    def __init__(self, params: dict, rng: random.Random) -> None:
        self._false_positive_rate: float = float(
            params.get("false_positive_rate", 0.15)
        )
        self._harvest_probability: float = float(
            params.get("credential_harvest_probability", 0.30)
        )
        self._privilege_weights: dict[str, dict[str, float]] = params.get(
            "credential_privilege_weights_by_node_type", {}
        )
        self._rng = rng
        self._credential_counter: int = 1  # cred_001 is the foothold seed
        # Safe default — overridden by set_file_harvest_probability() before
        # check_file_harvest() is ever called in normal operation. Default of
        # 0.0 means no file harvests occur if the setter is never called,
        # which is safe (silent degradation rather than AttributeError).
        self._params_file_harvest_probability: float = 0.0

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def check(
        self,
        node_id: str,
        node_type: str,
        username: str,
        current_credential_store: list[Credential],
    ) -> HallucinationResult:
        """
        Apply the hallucination check to an auth success event.

        Called by the traversal agent immediately after receiving an auth
        success, before any BFS queue or credential store update.

        Parameters
        ----------
        node_id : str
            The node that was successfully authenticated against.
        node_type : str
            The node_type attribute of that node (e.g. 'database').
        username : str
            The account used for authentication.
        current_credential_store : list[Credential]
            The attacker's current credential store. Used to determine
            whether a harvested credential represents a privilege escalation.

        Returns
        -------
        HallucinationResult
            The traversal agent acts on this result without knowing the
            internal sampling logic.
        """
        # Step 1 — hallucination check (fires FIRST, per spec ordering guarantee)
        if self._rng.random() < self._false_positive_rate:
            return HallucinationResult(
                is_hallucination=True,
                harvested_credential=None,
                privilege_escalation=False,
            )

        # Step 2 — real success: roll credential harvest probability
        if self._rng.random() >= self._harvest_probability:
            # Harvest roll did not trigger
            return HallucinationResult(
                is_hallucination=False,
                harvested_credential=None,
                privilege_escalation=False,
            )

        # Step 3 — harvest triggered: sample privilege level for this node type
        harvested = self._sample_credential(
            node_id=node_id,
            node_type=node_type,
            username=username,
        )

        # Step 4 — check for privilege escalation
        escalation = self._is_privilege_escalation(
            new_privilege=harvested.privilege,
            current_store=current_credential_store,
        )

        return HallucinationResult(
            is_hallucination=False,
            harvested_credential=harvested,
            privilege_escalation=escalation,
        )

    def check_file_harvest(
        self,
        node_id: str,
        node_type: str,
        username: str,
        current_credential_store: list[Credential],
    ) -> Credential | None:
        """
        Roll the file-based credential harvest probability independently.

        Called once per file_access event on a file_server node. Does NOT
        apply the hallucination check — file credential discovery is a
        separate causal path from auth-success credential discovery.

        Per the spec: "independent of auth success... produces file_access →
        credential_harvest event sequences without a preceding auth_attempt
        success."

        Parameters
        ----------
        node_id : str
        node_type : str
            Expected to be 'file_server' for all calls, but not enforced.
        username : str
        current_credential_store : list[Credential]
            Used for privilege escalation detection only.

        Returns
        -------
        Credential | None
            A harvested credential if the roll triggered, else None.
        """
        # Note: this uses file_credential_harvest_probability, which the
        # traversal agent passes via the params it reads. We read it here
        # from the same params dict for consistency.
        file_harvest_prob: float = float(
            self._params_file_harvest_probability
        )
        if self._rng.random() >= file_harvest_prob:
            return None
        return self._sample_credential(
            node_id=node_id,
            node_type=node_type,
            username=username,
        )

    def set_file_harvest_probability(self, prob: float) -> None:
        """
        Set the file credential harvest probability.

        Called by the traversal agent after construction, passing the value
        from behavioral_params.yaml. Kept separate from __init__ to avoid
        requiring a second params key lookup in the constructor.
        """
        self._params_file_harvest_probability: float = prob

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _sample_credential(
        self,
        node_id: str,
        node_type: str,
        username: str,
    ) -> Credential:
        """
        Sample a credential privilege level and return a new Credential.

        Privilege level is sampled from the weight distribution for the
        node type where the credential was found. Domain controllers and
        logging infrastructure yield high-privilege credentials far more
        often than workstations.
        """
        weights = self._privilege_weights.get(node_type, {})

        if not weights:
            # Fallback if node type has no weight config — standard_user only
            privilege = "standard_user"
        else:
            levels = list(weights.keys())
            probs = list(weights.values())
            privilege = self._rng.choices(levels, weights=probs, k=1)[0]

        self._credential_counter += 1
        cred_id = f"cred_{self._credential_counter:03d}"

        return Credential(
            credential_id=cred_id,
            username=username,
            privilege=privilege,
            source_node=node_id,
        )

    def _is_privilege_escalation(
        self,
        new_privilege: str,
        current_store: list[Credential],
    ) -> bool:
        """
        Return True if new_privilege exceeds the highest privilege currently
        in the credential store.

        A privilege escalation is a discrete frontier expansion event — the
        traversal agent must re-evaluate the reachable BFS frontier when this
        returns True.
        """
        if not current_store:
            return False

        current_max_level = max(
            PRIVILEGE_HIERARCHY.index(c.privilege)
            for c in current_store
            if c.privilege in PRIVILEGE_HIERARCHY
        )
        new_level = PRIVILEGE_HIERARCHY.index(new_privilege) \
            if new_privilege in PRIVILEGE_HIERARCHY else 0

        return new_level > current_max_level